# The URL the site will be built for
base_url = "https://snugnook.org"
title = "Snug Nook"
theme = "ametrine"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
accent_color = "hsl(32 95% 67%)"

[extra.nav]
# When set to true and [extra.fediverse] is defined, it will use avatar from
# said Mastodon account, otherwise it'll fallback to apple_touch_icon specified
# in [extra.meta] or its default value.
# Also accepts arbitrary filenames and URLs for custom images.
icon = "apple-touch-icon.png"
# Usage of an icon is heavily adviced. In case if none is provided, first two
# letters of the link name will be used instead.
# Any icon name from https://phosphoricons.com can be used.
links = [
    { url = "https://discord.com/invite/ksgyZgCvGx", name = "Discord Server", icon = "discord-logo" },
    { url = "https://matrix.to/#/#snug-nook-space:envs.net", name = "Matrix Space", icon = "matrix-logo" },
]

[extra.meta]
# Variables bellow accept either "true" or a filename.
# Favicon can also accept an emoji instead of a filename.
# File extension are being respected, so e.g. if favicon has .gif extension
# it'll be treated as an animated one.
# If set to "true" these will use the default filenames:
# favicon          = favicon.png
# apple_touch_icon = apple-touch-icon.png
# card             = card.png
favicon = "favicon.ico"
apple_touch_icon = true
card = false
