base_url = "https://snugnook.org"
title = "Snug Nook"
theme = "ametrine"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
github_alerts = true

[extra]
accent_color = "hsl(32 95% 67%)"

[extra.meta]
favicon = "favicon.ico"
apple_touch_icon = true
card = false

[extra.nav]
icon = true
links = [
    { url = "https://discord.com/invite/ksgyZgCvGx", name = "Discord Server", icon = "discord-logo" },
    { url = "https://matrix.to/#/#space:snugnook.org", name = "Matrix Space", icon = "matrix-logo" },
    { url = "https://bsky.app/profile/snugnook.org", name = "Bluesky profile", icon = "butterfly" },
    { url = "https://forums.snugnook.org", name = "Forums", icon = "arrow-bend-double-up-left" },
    { url = "https://wiki.snugnook.org", name = "Wiki", icon = "books" },
]

[extra.footer]
copyright = true
show_powered_by = true
show_timestamp = true
