base_url = "https://snugnook.org"
title = "Snug Nook"
description = "The community-focused community."
theme = "ametrine"
compile_sass = true
build_search_index = true
author = "The Snug Nook Team"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  # { name = "categories", feed = true },
]

[markdown]
smart_punctuation = true
bottom_footnotes = true
external_links_class = "external"
github_alerts = true

[extra]
# accent_color = "hsl(32 95% 67%)"
accent_color = "orange"
csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "style-src", domains = [
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "connect-src", domains = [
    "discord.com",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.meta]
favicon = "favicon.ico"
apple_touch_icon = true
card = false

[extra.nav]
icon = true
links = [
  { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
  { url = "https://discord.com/invite/ksgyZgCvGx", name = "Discord Server", icon = "discord-logo" },
  { url = "https://matrix.to/#/#space:snugnook.org", name = "Matrix Space", icon = "matrix-logo" },
  { url = "https://bsky.app/profile/snugnook.org", name = "Bluesky profile", icon = "butterfly" },
  { url = "https://forums.snugnook.org", name = "Forums", icon = "arrow-bend-double-up-left" },
  { url = "https://wiki.snugnook.org", name = "Wiki", icon = "books" },
]

[extra.footer]
copyright = true
show_powered_by = true
show_timestamp = true

[extra.analytics]
service = "umami"
id = "a1a80a4d-ade1-41c6-aa27-bb26acee4c40"
self_hosted_url = "https://stats.daudix.one"
do_not_track = false
